In [ ]:
import pandas as pd
import sqlite3
import matplotlib.pyplot as plt

In [ ]:
# GitHub API URL
url = "https://api.github.com/search/repositories?q=machine+learning&sort=stars&order=desc&per_page=100"

In [ ]:
# Read the data
data = pd.read_json(url)

In [ ]:
df = pd.DataFrame(data["items"].tolist())

In [ ]:
# Select needed columns
df = df[
    [
        "name",
        "owner",
        "language",
        "stargazers_count",
        "forks_count",
        "watchers_count",
        "open_issues_count",
        "created_at",
        "updated_at",
        "license"
    ]
]

In [ ]:
df["owner"] = df["owner"].str["login"]

df["license"] = df["license"].str["name"]

df["license"] = df["license"].fillna("No License")

In [ ]:
df.isnull().sum()

name                  0
owner                 0
language             23
stargazers_count      0
forks_count           0
watchers_count        0
open_issues_count     0
created_at            0
updated_at            0
license               0
dtype: int64

In [ ]:
# Handle missing values
df["language"] = df["language"].fillna("Unknown")

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
# Remove duplicates
df = df.drop_duplicates()

In [ ]:
# Change dates
df["created_at"] = pd.to_datetime(df["created_at"])
df["updated_at"] = pd.to_datetime(df["updated_at"])

In [ ]:
# Rename columns
df.rename(columns={
    "stargazers_count": "stars",
    "forks_count": "forks",
    "watchers_count": "watchers",
    "open_issues_count": "open_issues",
    "created_at": "created_date",
    "updated_at": "updated_date"
})

,name,owner,language,stars,forks,watchers,open_issues,created_date,updated_date,license
0,tensorflow,tensorflow,C++,197043,76041,197043,2858,2015-11-07 01:19:20+00:00,2026-08-15 21:11:33+00:00,Apache License 2.0
1,transformers,huggingface,Python,164117,34249,164117,2382,2018-10-29 13:56:00+00:00,2026-08-15 20:58:19+00:00,Apache License 2.0
2,ML-For-Beginners,microsoft,Jupyter Notebook,89413,21944,89413,11,2021-03-03 01:34:05+00:00,2026-08-15 20:47:15+00:00,MIT License
3,funNLP,fighting41love,Python,82481,15267,82481,53,2018-08-21 11:20:39+00:00,2026-08-15 20:48:18+00:00,No License
4,awesome-machine-learning,josephmisiti,Python,74045,15614,74045,24,2014-07-15 19:11:19+00:00,2026-08-15 20:01:06+00:00,Other
...,...,...,...,...,...,...,...,...,...,...
95,Machine-learning-learning-notes,Vay-keen,Unknown,7763,1879,7763,28,2018-03-24 06:48:10+00:00,2026-08-14 17:10:02+00:00,No License
96,awesome-youtubers,JoseDeFreitas,Markdown,7682,493,7682,2,2020-08-25 14:18:15+00:00,2026-08-15 16:19:26+00:00,Creative Commons Zero v1.0 Universal
97,Learn_Machine_Learning_in_3_Months,llSourcell,Unknown,7607,2311,7607,19,2018-03-02 10:59:53+00:00,2026-08-14 15:37:04+00:00,No License
98,h2o-3,h2oai,Jupyter Notebook,7503,2027,7503,2880,2014-03-03 16:08:07+00:00,2026-08-15 07:17:42+00:00,Apache License 2.0
99,industry-machine-learning,firmai,Jupyter Notebook,7484,1249,7484,3,2019-05-03 05:08:15+00:00,2026-08-14 03:11:39+00:00,No License

In [ ]:
# Save the file
df.to_csv("github_projects.csv")

In [ ]:
print(df.head())

                       name           owner          language  \
0                tensorflow      tensorflow               C++
1              transformers     huggingface            Python
2          ML-For-Beginners       microsoft  Jupyter Notebook
3                    funNLP  fighting41love            Python
4  awesome-machine-learning    josephmisiti            Python

   stargazers_count  forks_count  watchers_count  open_issues_count  \
0            197043        76041          197043               2858
1            164117        34249          164117               2382
2             89413        21944           89413                 11
3             82481        15267           82481                 53
4             74045        15614           74045                 24

                 created_at                updated_at             license
0 2015-11-07 01:19:20+00:00 2026-08-15 21:11:33+00:00  Apache License 2.0
1 2018-10-29 13:56:00+00:00 2026-08-15 20:58:19+00:00  Apache License 2.0
2 2021-03-03 01:34:05+00:00 2026-08-15 20:47:15+00:00         MIT License
3 2018-08-21 11:20:39+00:00 2026-08-15 20:48:18+00:00          No License
4 2014-07-15 19:11:19+00:00 2026-08-15 20:01:06+00:00               Other

In [ ]:
df.dtypes

name                              object
owner                             object
language                          object
stargazers_count                   int64
forks_count                        int64
watchers_count                     int64
open_issues_count                  int64
created_at           datetime64[ns, UTC]
updated_at           datetime64[ns, UTC]
license                           object
dtype: object

In [ ]:
df.shape

(100, 10)

In [ ]:
df.columns

Index(['name', 'owner', 'language', 'stargazers_count', 'forks_count',
       'watchers_count', 'open_issues_count', 'created_at', 'updated_at',
       'license'],
      dtype='object')

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   name               100 non-null    object
 1   owner              100 non-null    object
 2   language           100 non-null    object
 3   stargazers_count   100 non-null    int64
 4   forks_count        100 non-null    int64
 5   watchers_count     100 non-null    int64
 6   open_issues_count  100 non-null    int64
 7   created_at         100 non-null    datetime64[ns, UTC]
 8   updated_at         100 non-null    datetime64[ns, UTC]
 9   license            100 non-null    object
dtypes: datetime64[ns, UTC](2), int64(4), object(4)
memory usage: 7.9+ KB
None

In [ ]:
# Load the CSV
df = pd.read_csv("github_projects.csv")

In [ ]:
df.rename(columns={
    'stargazers_count': 'stars',
    'forks_count': 'forks',
    'watchers_count': 'watchers',
    'open_issues_count': 'open_issues',
    'created_at': 'created_date',
    'updated_at': 'updated_date'
})

,Unnamed: 0,name,owner,language,stars,forks,watchers,open_issues,created_date,updated_date,license
0,0,tensorflow,tensorflow,C++,197043,76041,197043,2858,2015-11-07 01:19:20+00:00,2026-08-15 21:11:33+00:00,Apache License 2.0
1,1,transformers,huggingface,Python,164117,34249,164117,2382,2018-10-29 13:56:00+00:00,2026-08-15 20:58:19+00:00,Apache License 2.0
2,2,ML-For-Beginners,microsoft,Jupyter Notebook,89413,21944,89413,11,2021-03-03 01:34:05+00:00,2026-08-15 20:47:15+00:00,MIT License
3,3,funNLP,fighting41love,Python,82481,15267,82481,53,2018-08-21 11:20:39+00:00,2026-08-15 20:48:18+00:00,No License
4,4,awesome-machine-learning,josephmisiti,Python,74045,15614,74045,24,2014-07-15 19:11:19+00:00,2026-08-15 20:01:06+00:00,Other
...,...,...,...,...,...,...,...,...,...,...,...
95,95,Machine-learning-learning-notes,Vay-keen,Unknown,7763,1879,7763,28,2018-03-24 06:48:10+00:00,2026-08-14 17:10:02+00:00,No License
96,96,awesome-youtubers,JoseDeFreitas,Markdown,7682,493,7682,2,2020-08-25 14:18:15+00:00,2026-08-15 16:19:26+00:00,Creative Commons Zero v1.0 Universal
97,97,Learn_Machine_Learning_in_3_Months,llSourcell,Unknown,7607,2311,7607,19,2018-03-02 10:59:53+00:00,2026-08-14 15:37:04+00:00,No License
98,98,h2o-3,h2oai,Jupyter Notebook,7503,2027,7503,2880,2014-03-03 16:08:07+00:00,2026-08-15 07:17:42+00:00,Apache License 2.0
99,99,industry-machine-learning,firmai,Jupyter Notebook,7484,1249,7484,3,2019-05-03 05:08:15+00:00,2026-08-14 03:11:39+00:00,No License

In [ ]:
# Create database
conn = sqlite3.connect("github_projects.db")

df.to_sql("Repositories", conn, if_exists="replace")

100

In [ ]:
M = 'SELECT name, stars FROM Repositories WHERE stars > 10000'
pd.read_sql_query(M, conn)

                               name   stars
0                        tensorflow  197043
1                      transformers  164117
2                  ML-For-Beginners   89413
3                            funNLP   82481
4          awesome-machine-learning   74045
..                              ...     ...
65  machine-learning-systems-design   10516
66                 Machine-Learning   10368
67           machine-learning-notes   10326
68              3D-Machine-Learning   10193
69                             tpot   10053

[70 rows x 2 columns]

In [ ]:
M = "SELECT name FROM Repositories WHERE name LIKE '%Machine%'"
pd.read_sql_query(M, conn)

                                                 name
0                            awesome-machine-learning
1   500-AI-Machine-learning-Deep-learning-Computer...
2             machine-learning-for-software-engineers
3                           homemade-machine-learning
4                 awesome-production-machine-learning
5                        machine-learning-for-trading
6                    stanford-cs-229-machine-learning
7                          Machine-Learning-Tutorials
8                           machine-learning-zoomcamp
9                          machine-learning-interview
10                       python-machine-learning-book
11                         dive-into-machine-learning
12                    machine-learning-systems-design
13                                   Machine-Learning
14                             machine-learning-notes
15                                3D-Machine-Learning
16                                    machinelearning
17                          machine_learning_examples
18  state-of-the-art-result-for-machine-learning-p...
19                         financial-machine-learning
20                                    machinelearning
21                             MachineLearning_Python
22                        Machine-Learning-Collection
23                       machine-learning-cheat-sheet
24                           machine-learning-roadmap
25                       machine-learning-yearning-cn
26           Machine-Learning-Specialization-Coursera
27                    Machine-learning-learning-notes
28                 Learn_Machine_Learning_in_3_Months
29                          industry-machine-learning

In [ ]:
M = 'SELECT name, stars, forks FROM Repositories WHERE stars > 10000 AND forks > 1000'
pd.read_sql_query(M, conn)

                               name   stars  forks
0                        tensorflow  197043  76041
1                      transformers  164117  34249
2                  ML-For-Beginners   89413  21944
3                            funNLP   82481  15267
4          awesome-machine-learning   74045  15614
..                              ...     ...    ...
64  machine-learning-systems-design   10516   1628
65                 Machine-Learning   10368   5065
66           machine-learning-notes   10326   1825
67              3D-Machine-Learning   10193   1797
68                             tpot   10053   1564

[69 rows x 3 columns]

In [ ]:
M = "SELECT name, language FROM Repositories WHERE language = 'Python' OR language = 'JavaScript'"
pd.read_sql_query(M, conn)

                                  name    language
0                         transformers      Python
1                               funNLP      Python
2             awesome-machine-learning      Python
3                         scikit-learn      Python
4                               gradio      Python
5                               netron  JavaScript
6                      ML-From-Scratch      Python
7   linkedin-skill-assessments-quizzes      Python
8                          cs249r_book      Python
9                                 onnx      Python
10                                rasa      Python
11                      ml-engineering      Python
12                            numpy-ml      Python
13                     transformers.js  JavaScript
14                              imgaug      Python
15                          ChatterBot      Python
16                                 nni      Python
17                                 ivy      Python
18                                 tvm      Python
19                                lime  JavaScript
20                            cleanlab      Python
21                        MLAlgorithms      Python
22                               dolly      Python
23                             doccano      Python
24                         mlcourse.ai      Python
25                    Machine-Learning      Python
26                              sktime      Python
27           machine_learning_examples      Python
28                             pattern      Python
29          financial-machine-learning      Python
30              MachineLearning_Python      Python
31         Machine-Learning-Collection      Python
32                        auto-sklearn      Python

In [ ]:
M = "SELECT name, language FROM Repositories WHERE NOT language = 'Python'"
pd.read_sql_query(M, conn)

                                                 name          language
0                                          tensorflow               C++
1                                    ML-For-Beginners  Jupyter Notebook
2   500-AI-Machine-learning-Deep-learning-Computer...           Unknown
3                                         C-Plus-Plus               C++
4                                              netron        JavaScript
..                                                ...               ...
65                    Machine-learning-learning-notes           Unknown
66                                  awesome-youtubers          Markdown
67                 Learn_Machine_Learning_in_3_Months           Unknown
68                                              h2o-3  Jupyter Notebook
69                          industry-machine-learning  Jupyter Notebook

[70 rows x 2 columns]

In [ ]:
M = 'SELECT name, stars FROM Repositories ORDER BY stars DESC LIMIT 10'
pd.read_sql_query(M, conn)

                                                name   stars
0                                         tensorflow  197043
1                                       transformers  164117
2                                   ML-For-Beginners   89413
3                                             funNLP   82481
4                           awesome-machine-learning   74045
5                                       scikit-learn   66957
6                                             gradio   43365
7  500-AI-Machine-learning-Deep-learning-Computer...   36283
8                                        C-Plus-Plus   34584
9                                             netron   33354

In [ ]:
M = 'SELECT COUNT(*) AS total_repositories FROM Repositories'
pd.read_sql_query(M, conn)

   total_repositories
0                 100

In [ ]:
M = 'SELECT AVG(stars) AS average_stars FROM Repositories'
pd.read_sql_query(M, conn)

   average_stars
0       20790.68

In [ ]:
M = 'SELECT language, COUNT(*) AS total FROM Repositories GROUP BY language HAVING COUNT(*) > 5'
pd.read_sql_query(M, conn)

           language  total
0               C++     12
1  Jupyter Notebook     19
2            Python     30
3           Unknown     23